[build]
  functions = "netlify/functions"
  publish = "public"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/frame"
  to = "/.netlify/functions/frame"
  status = 200

[[redirects]]
  from = "/image"
  to = "/.netlify/functions/image"
  status = 200

[dev]
  framework = "#static"
  autoLaunch = true
