[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/frame"
  to = "/.netlify/functions/frame"
  status = 200

[[redirects]]
  from = "/image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/trade"
  to = "/.netlify/functions/trade"
  status = 200


[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#static"
  autoLaunch = true
